- user-service/.gitignore
- user-service/build.gradle
- user-service/http/User.http
- user-service/src/main/java/kr/mybrary/userservice/authentication/domain/AuthenticationService.java
- user-service/src/main/java/kr/mybrary/userservice/authentication/domain/impl/AuthenticationServiceImpl.java
- user-service/src/main/java/kr/mybrary/userservice/authentication/domain/login/LoginException.java
- user-service/src/main/java/kr/mybrary/userservice/authentication/domain/login/handler/LoginFailureHandler.java
- user-service/src/main/java/kr/mybrary/userservice/authentication/domain/oauth2/CustomOAuth2User.java
- user-service/src/main/java/kr/mybrary/userservice/authentication/domain/oauth2/OAuth2Exception.java
- user-service/src/main/java/kr/mybrary/userservice/authentication/domain/oauth2/OAuthAttributes.java
- user-service/src/main/java/kr/mybrary/userservice/authentication/domain/oauth2/handler/OAuth2LoginFailureHandler.java
- user-service/src/main/java/kr/mybrary/userservice/authentication/domain/oauth2/handler/OAuth2LoginSuccessHandler.java
- user-service/src/main/java/kr/mybrary/userservice/authentication/domain/oauth2/service/CustomOAuth2UserService.java
- user-service/src/main/java/kr/mybrary/userservice/authentication/domain/oauth2/userinfo/GoogleOAuth2UserInfo.java
- user-service/src/main/java/kr/mybrary/userservice/authentication/domain/oauth2/userinfo/KakaoOAuth2UserInfo.java
- user-service/src/main/java/kr/mybrary/userservice/authentication/domain/oauth2/userinfo/NaverOAuth2UserInfo.java
- user-service/src/main/java/kr/mybrary/userservice/authentication/domain/oauth2/userinfo/OAuth2UserInfo.java
- user-service/src/main/java/kr/mybrary/userservice/authentication/presentation/dto/request/SignUpRequest.java
- user-service/src/main/java/kr/mybrary/userservice/global/config/WebSecurityConfig.java
- user-service/src/main/java/kr/mybrary/userservice/global/jwt/service/JwtService.java
- user-service/src/main/java/kr/mybrary/userservice/user/persistence/Role.java
- user-service/src/main/java/kr/mybrary/userservice/user/persistence/User.java
- user-service/src/main/resources/application-oauth.yml
- user-service/src/main/resources/application.yml
- user-service/src/test/java/kr/mybrary/userservice/UserServiceApplicationTests.java
- user-service/src/test/java/kr/mybrary/userservice/authentication/domain/impl/AuthenticationServiceImplTest.java
- user-service/src/test/java/kr/mybrary/userservice/authentication/domain/login/LoginTest.java
- user-service/src/test/java/kr/mybrary/userservice/authentication/domain/oauth/OAuth2Test.java
1. http://localhost:8080/oauth2/authorization/google 으로 요청을 보내면 구글 로그인 페이지로 리다이렉트 된다
2. 최초 로그인 시 구글 소셜 로그인 회원으로 회원 가입 된다
- 소셜 아이디, 닉네임, 이메일, 프로필 사진 url을 받아와서 저장 (닉네임은 랜덤 5자리 숫자를 덧붙여서 저장)
- 아이디와 비밀번호는 UUID로 생성 (비밀번호는 암호화하여 저장)
3. 다시 해당 계정으로 로그인 하게 되면 기존에 등록된 회원 정보를 바탕으로 로그인 성공
1. http://localhost:8080/oauth2/authorization/kakao 으로 요청을 보내면 카카오 로그인 페이지로 리다이렉트 된다
2. 최초 로그인 시 카카오 소셜 로그인 회원으로 회원 가입 된다
- 소셜 아이디, 닉네임, 프로필 사진 url을 받아와서 저장 (닉네임은 랜덤 5자리 숫자를 덧붙여서 저장)
- 이메일은 선택 사항이므로 받아오지 못한다면 null로 저장
- 아이디와 비밀번호는 UUID로 생성 (비밀번호는 암호화하여 저장)
3. 다시 해당 계정으로 로그인 하게 되면 기존에 등록된 회원 정보를 바탕으로 로그인 성공
1. http://localhost:8080/oauth2/authorization/naver 으로 요청을 보내면 네이버 로그인 페이지로 리다이렉트 된다
2. 최초 로그인 시 네이버 소셜 로그인 회원으로 회원 가입 된다
- 소셜 아이디, 닉네임, 이메일, 프로필 사진 url을 받아와서 저장 (닉네임은 랜덤 5자리 숫자를 덧붙여서 저장)
- 아이디와 비밀번호는 UUID로 생성 …
> [IDLE-59] feat: 소셜 로그인 기능 구현

- frontend/android/app/src/main/AndroidManifest.xml
- frontend/ios/Flutter/Debug.xcconfig
- frontend/ios/Flutter/Release.xcconfig
- frontend/ios/Podfile
- frontend/ios/Podfile.lock
- frontend/ios/Runner.xcodeproj/project.pbxproj
- frontend/ios/Runner.xcworkspace/contents.xcworkspacedata
- frontend/ios/Runner/Info.plist
- frontend/lib/components/login/login_input_component.dart
- frontend/lib/components/login/login_logo_component.dart
- frontend/lib/constants/color.dart
- frontend/lib/data/network/service/auth_apis.dart
- frontend/lib/main.dart
- frontend/lib/screens/auth/find_password_screen.dart
- frontend/lib/screens/auth/login_screen.dart
- frontend/lib/screens/auth/reset_verify_screen.dart
- frontend/lib/screens/auth/sign_up_screen.dart
- frontend/lib/screens/auth/sign_up_verify_screen.dart
- frontend/lib/screens/home_screen.dart
- frontend/lib/utilities/logic.dart
- frontend/lib/utilities/regexps.dart
- frontend/pubspec.lock
- frontend/pubspec.yaml
- frontend/test/shared/res/regexps_test.dart
<br><br>
- 패스워드 찾기 페이지 UI 구현 진행
- 비밀번호를 잊으셨나요? 를 클릭하면 페이지 이동
- 아이디를 입력하면 가입한 이메일로 임시 비밀번호 발송
- 아이디 값에 따른 에러 처리 (유효성/존재여부)
- 성공 후, 임시 비밀번호가 발송되면 아이디 input 비활성화
- 세부 작업 사항
- 유효성 검사에 사용되는 정규표현식은 utilities/regexps 파일에 공통으로 관리
- 공통 관리되는 정규표현식 및 색상으로 모두 수정
<br><br>
<br><br>
<br><br>
- 추후 사용될 토스트 메세지 관련 패키지를 설치하고, 테스트 중에 있습니다.
- 비밀번호 재설정 관련 사용자 시나리오에 대해 다음에 같이 이야기를 나눠보면 좋을 것 같습니다.
- PR이 완료되면, 바로 메인 및 검색 페이지 구현으로 넘어가보도록 하겠습니다.
> [IDLE-69] feat: 패스워드 찾기 페이지 UI 구현

- backend/book-service/src/main/java/kr/mybrary/bookservice/book/domain/dto/request/BookCreateServiceRequest.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/book/presentation/dto/request/BookCreateRequest.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/booksearch/domain/dto/BookSearchResultDto.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/domain/MyBookService.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/domain/dto/MyBookDtoMapper.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/domain/dto/request/MyBookCreateServiceRequest.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/domain/dto/request/MyBookDetailServiceRequest.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/domain/dto/request/MyBookFindAllServiceRequest.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/domain/exception/MyBookAccessDeniedException.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/domain/exception/MyBookNotFoundException.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/persistence/MyBook.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/persistence/repository/MyBookRepository.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/presentation/MyBookController.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/presentation/dto/request/MyBookCreateRequest.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/presentation/dto/response/MyBookDetailResponse.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/presentation/dto/response/MyBookElementResponse.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/book/BookTestData.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/mybook/MybookTestData.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/mybook/domain/MyBookServiceTest.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/mybook/domain/dto/MyBookDtoMapperTest.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/mybook/persistence/MyBookRepositoryTest.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/mybook/presentation/MyBookControllerTest.java
- isPublic, isSharable, isExchangable 에서 is 접두사 제거 (showable, sharable, exchangeable)
- boolean에 대한 Getter 이슈와 Mapstruct 매핑 이슈로 인해 boolean 변수 네이밍에서 is 를 제거하기로 협의
- 마이북 전체조회 : GET "/api/v1/users/{userId}/mybooks"
- 마이북 상세조회 : GET "/api/v1/users/{userId}/mybooks/{mybookId}"
- 각 예외 상황 처리 및 단위 테스트 작성
- 로그인한 사용자 아이디는 Http Request Header를 통해 전달받도록 구현 ("USER-ID")
- 테스트 코드에 필요한 테스트 데이터 추가
- 각 계층 단위 테스트 작성
- Domain 계층, 여러 예외 상황에 대해서도 테스트 코드 작성
- Persistence 계층, 작성한 쿼리 메서드가 의도한 쿼리를 생성하고 동작하는지 테스트 코드 작성
- mapStruct 매핑에 대한 테스트 코드 작성
<br><br>
<br><br>
<br><br>
> [IDLE-111] feat: 마이북 전체 조회/상세 조회 API 개발

- user-service/build.gradle
- user-service/src/main/java/kr/mybrary/userservice/global/exception/ApplicationException.java
- user-service/src/main/java/kr/mybrary/userservice/global/exception/GlobalExceptionHandler.java
- user-service/src/main/java/kr/mybrary/userservice/user/domain/UserService.java
- user-service/src/main/java/kr/mybrary/userservice/user/domain/UserServiceImpl.java
- user-service/src/main/java/kr/mybrary/userservice/user/domain/dto/UserMapper.java
- user-service/src/main/java/kr/mybrary/userservice/user/domain/dto/response/ProfileImageUrlServiceResponse.java
- user-service/src/main/java/kr/mybrary/userservice/user/domain/exception/DuplicateEmailException.java
- user-service/src/main/java/kr/mybrary/userservice/user/domain/exception/DuplicateLoginIdException.java
- user-service/src/main/java/kr/mybrary/userservice/user/domain/exception/DuplicateNicknameException.java
- user-service/src/main/java/kr/mybrary/userservice/user/domain/exception/DuplicateUserInfoException.java
- user-service/src/main/java/kr/mybrary/userservice/user/domain/exception/ProfileImageUrlNotFoundException.java
- user-service/src/main/java/kr/mybrary/userservice/user/domain/exception/UserNotFoundException.java
- user-service/src/main/java/kr/mybrary/userservice/user/presentation/UserController.java
- user-service/src/test/java/kr/mybrary/userservice/user/UserFixture.java
- user-service/src/test/java/kr/mybrary/userservice/user/UserTestData.java
- user-service/src/test/java/kr/mybrary/userservice/user/domain/UserServiceImplTest.java
- user-service/src/test/java/kr/mybrary/userservice/user/domain/dto/UserMapperTest.java
- user-service/src/test/java/kr/mybrary/userservice/user/persistence/repository/UserRepositoryTest.java
- user-service/src/test/java/kr/mybrary/userservice/user/presentation/UserControllerTest.java
- 로그인 아이디를 통해 프로필/ 프로필 사진 조회 가능
- 로그인 아이디로 사용자를 찾을 수 없다면 UserNotFoundException 반환
- 사용자에게 프로필 이미지 URL이 없다면 ProfileImageUrlNotFoundException 반환
- 기본 이미지 URL조차 없는 경우 문제가 있다고 판단하여, 예외 처리되도록 구현했습니다
- Enum을 통해 UserFixture 생성
- UserTestData 클래스에 테스트 데이터 생성 함수 추가
- UserRepositoryTest
- UserMapperTest
<br><br>
<br><br>
🏃‍♂️ 보통 : 최대한 빠르게 리뷰 부탁드립니다.
(곧바로 프로필 수정/삭제 기능 개발하려구 합니다 ^-^,,)
<br><br>
[Test Data 만들기 (Builder vs Object Mother)](https://velog.io/@gwichanlee/Test-Data-%EB%A7%8C%EB%93%A4%EA%B8%B0-Builder-vs-Object-Mother)
> [IDLE-105] feat: 사용자 프로필 조회 API 개발

- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/domain/MyBookService.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/domain/dto/MyBookDtoMapper.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/domain/dto/request/MybookUpdateServiceRequest.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/persistence/MyBook.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/presentation/MyBookController.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/presentation/dto/request/MyBookUpdateRequest.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/presentation/dto/response/MyBookUpdateResponse.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/book/presentation/BookControllerTest.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/booksearch/presentation/BookSearchControllerTest.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/mybook/MybookDtoTestData.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/mybook/domain/MyBookServiceTest.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/mybook/domain/dto/MyBookDtoMapperTest.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/mybook/presentation/MyBookControllerTest.java
- PUT "/api/v1/mybooks/{mybookId}" : 마이북 속성 수정 API 개발
- 수정 가능한 필드값 (의미태그는 추후에 개발 예정)
```
private boolean showable;
private boolean exchangeable;
private boolean shareable;
private ReadStatus readStatus;
private LocalDateTime startDateOfPossession;
```
- 응답값  : 수정가능한 필드값과 동일 (수정된 필드값에 대해서 응답)
- 업데이트 이후 마이북 상세보기 조회시, 조회 API를 호출하지 않고 해당 응답값을 바탕으로 상세보기 페이지를 디스플레이를 하도록 위함.
- 혹은 로그에 활용하기 위함
- 테스트 코드 작성
<br/>
- Swagger UI에 생성한 rest docs를 표시하기 위해 requestSchema와 responseSchema 형식 수정
- 하이픈과 띄어쓰기 제거 -> 언더바로 통일
<br><br>
<br><br>
<br><br>
> [IDLE-113] feat: 마이북 속성 설정  및 수정 API 개발

- user-service/src/main/java/kr/mybrary/userservice/global/BaseEntity.java
- user-service/src/main/java/kr/mybrary/userservice/user/domain/UserServiceImpl.java
- user-service/src/main/java/kr/mybrary/userservice/user/domain/exception/follow/DuplicateFollowException.java
- user-service/src/main/java/kr/mybrary/userservice/user/domain/exception/follow/SameSourceTargetUserException.java
- user-service/src/main/java/kr/mybrary/userservice/user/domain/exception/io/EmptyFileException.java
- user-service/src/main/java/kr/mybrary/userservice/user/domain/exception/io/FileInputStreamException.java
- user-service/src/main/java/kr/mybrary/userservice/user/domain/storage/AmazonS3Service.java
- user-service/src/main/java/kr/mybrary/userservice/user/persistence/Follow.java
- user-service/src/main/java/kr/mybrary/userservice/user/persistence/User.java
- user-service/src/test/java/kr/mybrary/userservice/user/UserFixture.java
- user-service/src/test/java/kr/mybrary/userservice/user/domain/UserServiceImplTest.java
- user-service/src/test/java/kr/mybrary/userservice/user/domain/follow/FollowTest.java
- 요청된 사용자의 팔로워 목록을 조회합니다
- follow 테이블에서 deleted가 false이면서 target_id가 자신인 데이터들만 읽어옵니다
- 요청된 사용자의 팔로잉 목록을 조회합니다
- follow 테이블에서 deleted가 false이면서 source_id가 자신인 데이터들만 읽어옵니다
- 요청된 사용자를 팔로우 합니다
- 요청한 사용자와 요청된 사용자가 같으면 예외가 발생합니다
- 이미 팔로우 한 사용자라면 예외가 발생합니다
- 요청된 사용자를 언팔로우 합니다
- 요청한 사용자와 요청된 사용자가 같으면 예외가 발생합니다
- 이미 언팔로우 상태인 사용자라도 예외가 발생하지 않습니다 (removeIf 사용)
```
public void unfollow(User target) {
this.followings.removeIf(follow -> follow.getTarget().equals(target));
target.followers.removeIf(follow -> follow.getSource().equals(this));
}
```
- 요청된 사용자를 팔로워 목록에서 삭제합니다
- 요청된 사용자로 하여금 자신을 언팔로우 하도록 동작합니다
- 요청한 사용자와 요청된 사용자가 같으면 예외가 발생합니다
팔로우 기능 테스트 관련 이슈
1. 요청에 따라 followers, followings 변수 값이 유동적으로 바뀜 -> UserFixture 사용이 어려워짐
2. 팔로우 요청 후 팔로잉 목록에 추가된 사용자 객체와 요청된 사용자 객체가 같은 지 동일성 비교가 어려움 -> 단순히 size 정도만 …
> [IDLE-107] feat: 팔로잉 기능 구현 

- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/domain/MyBookService.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/domain/dto/request/MybookUpdateServiceRequest.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/persistence/MyBook.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/presentation/dto/request/MyBookUpdateRequest.java
- backend/book-service/src/main/resources/application-dev.yml
- backend/book-service/src/main/resources/application-local.yml
- backend/book-service/src/main/resources/application-test.yml
- backend/book-service/src/main/resources/bootstrap.yml
- backend/book-service/src/test/java/kr/mybrary/bookservice/mybook/MybookDtoTestData.java
- local : 로컬 환경에서 개발할 때 사용하는 환경
- eurekaClient disable
- bus-amqp 라이브러리 비활성화 실패 .. 일단 rabbitmq를 구동시키고 로컬에서 개발중입니다.
- 환경 변수를 통해서 각 API 키를 주입
- test : 테스트 코드가 동작하는 환경
- 테스트용 데이터 베이스 사용
- 로깅시, sql 파라미터가 표시되도록 설정
- dev : 배포해서, 클라이언트와 API 테스트를 하기 위한 환경
- config server로 부터 전달되는 설정 모두 삭제
prod 환경은 1차 릴리즈에 작성예정.
- 중복 코드 메서드 추출
- 조건절 !을 사용하지 않고, 의미 있는 메서드 추출
<br><br>
<br><br>
<br><br>
```
spring:
autoconfigure:
exclude:
- org.springframework.cloud.bus.autoconfigure.BusAutoConfiguration
```
application-local.yml 에 해당 코드를 작성하여, bus-amqp 라이브러리를 비활성화하려 했지만 동작하지 않음.
> [IDLE-136] refactor: 4차 SPRINT까지 book-service 코드 리펙토링

- user-service/src/main/java/kr/mybrary/userservice/global/exception/GlobalExceptionHandler.java
- user-service/src/main/java/kr/mybrary/userservice/user/domain/UserService.java
- user-service/src/main/java/kr/mybrary/userservice/user/domain/UserServiceImpl.java
- user-service/src/main/java/kr/mybrary/userservice/user/domain/dto/UserMapper.java
- user-service/src/main/java/kr/mybrary/userservice/user/domain/dto/response/SearchServiceResponse.java
- user-service/src/main/java/kr/mybrary/userservice/user/domain/exception/user/UserNotSearchedException.java
- user-service/src/main/java/kr/mybrary/userservice/user/persistence/repository/UserRepository.java
- user-service/src/main/java/kr/mybrary/userservice/user/presentation/UserController.java
- user-service/src/main/java/kr/mybrary/userservice/user/presentation/dto/request/SignUpRequest.java
- user-service/src/test/java/kr/mybrary/userservice/user/UserFixture.java
- user-service/src/test/java/kr/mybrary/userservice/user/domain/UserServiceImplTest.java
- user-service/src/test/java/kr/mybrary/userservice/user/domain/dto/UserMapperTest.java
- user-service/src/test/java/kr/mybrary/userservice/user/persistence/repository/UserRepositoryTest.java
- user-service/src/test/java/kr/mybrary/userservice/user/presentation/UserControllerTest.java
- user-service/src/test/java/kr/mybrary/userservice/user/presentation/dto/request/ProfileUpdateRequestValidationTest.java
- user-service/src/test/java/kr/mybrary/userservice/user/presentation/dto/request/SignUpRequestValidationTest.java
- 요청
- GET api/v1/users/search?nickname={검색할 닉네임}
- 응답
- {로그인 아이디, 닉네임, 프로필 이미지 url}
- 검색된 사용자가 없다면 예외 발생
- Validator 에서 발생한 예외 처리 (예외 원인들을 모두 메시지로 반환)
- 예) 닉네임, 비밀번호 형식이 맞지 않는 경우
- SignUpRequest Validation 테스트
- ProfileUpdateRequest Validation 테스트
- 추후 다른 요청 DTO 에도 Validator 설정 및 Validation 테스트 진행 예정
- 저장된 회원 닉네임이 nickname, nickname123, nick, 닉네임, hellohello, hihihihi 일 때, nickname 으로 회원 검색 시 nickname, nickname123 회원 반환
- 검색된 사용자가 없으면 예외 발생
<br><br>
<br><br>
<br><br>
- 사용자 검색 결과에 리턴할 프로필 이미지는 썸네일용 작은 이미지여도 될 것 같습니다. 다음에 이미지 압축해서 썸네일용 프로필 이미지를 따로 저장하는 것을 고려해보겠습니다.
- 이미지 url로 s3 오브젝트 url을 리턴하고 있는데, 버킷을 private으로 보호하기 위해 자체 이미지 호출 api를 생성하는 것을 고려해보겠습니다.
> [IDLE-139] feat: 사용자 검색 기능 개발

- backend/book-service/.github/workflows/rest-docs.yml
- book-service 에서 pull-request 혹은 push가 될 때, ./gradlew openapi3를 실행하여 자동으로 restdocs 파일을 s3로 올리도록 github actions 파일 생성
- 테스트 ..
- 잘 안될 수도 있어요.. 현재 master가 아닌 다른 브랜치에서 작업하여 반영이 안된 것으로 보아 리베이스합니다!
<br><br>
<br><br>
<br><br>
https://tech.trenbe.com/2023/01/30/%EB%A7%88%EC%9D%B4%ED%81%AC%EB%A1%9C-%EC%84%9C%EB%B9%84%EC%8A%A4-%ED%99%98%EA%B2%BD%EC%97%90%EC%84%9C-%ED%86%B5%ED%95%A9%EB%90%9C-API-%EB%AC%B8%EC%84%9C-%EC%84%9C%EB%B2%84-%EA%B5%AC%EC%B6%95%ED%95%98%EA%B8%B0.html
> [IDLE-167] feat: openapi rest docs github actions 연동

- backend/user-service/src/main/java/kr/mybrary/userservice/interest/domain/InterestService.java
- backend/user-service/src/main/java/kr/mybrary/userservice/interest/domain/InterestServiceImpl.java
- backend/user-service/src/main/java/kr/mybrary/userservice/interest/domain/dto/request/UserInterestUpdateServiceRequest.java
- backend/user-service/src/main/java/kr/mybrary/userservice/interest/domain/exception/DuplicateUserInterestUpdateRequestException.java
- backend/user-service/src/main/java/kr/mybrary/userservice/interest/domain/exception/InterestNotFoundException.java
- backend/user-service/src/main/java/kr/mybrary/userservice/interest/domain/exception/UserInterestUpdateRequestSizeExceededException.java
- backend/user-service/src/main/java/kr/mybrary/userservice/interest/persistence/UserInterest.java
- backend/user-service/src/main/java/kr/mybrary/userservice/interest/persistence/repository/UserInterestRepository.java
- backend/user-service/src/main/java/kr/mybrary/userservice/interest/presentation/InterestController.java
- backend/user-service/src/main/java/kr/mybrary/userservice/interest/presentation/dto/request/UserInterestUpdateRequest.java
- backend/user-service/src/test/java/kr/mybrary/userservice/interest/domain/InterestServiceImplTest.java
- backend/user-service/src/test/java/kr/mybrary/userservice/interest/persistence/repository/UserInterestRepositoryTest.java
- backend/user-service/src/test/java/kr/mybrary/userservice/interest/presentation/InterestControllerTest.java
- 요청) PUT api/v1/users/{userId}/interests
```
{
"interestRequests": [
{
"id": 1,
"name": "국내소설"
},
{
"id": 2,
"name": "외국소설"
}
]
}
```
- 응답
```
{
"status": "200 OK",
"message": "사용자의 관심사를 수정했습니다.",
"data": {
"loginId": "loginId",
"userInterests": [
{
"id": 1,
"name": "국내소설"
},
{
"id": 2,
"name": "외국소설"
}
]
}
}
```
- 삭제 API는 따로 없습니다. 요청 시 interestRequests를 빈 배열로 보내주시면 삭제 처리 됩니다!
- 사용자에게 중복된 관심사가 저장될 수 없도록 user_id와 interest_id를 묶어 unique 제약 조건을 걸어주었습니다.
```
@Table(name = "users_interests",
uniqueConstraints = {
@UniqueConstraint(
name = "uk_users_interests_user_id_interest_id",
columnNames = {"user_id", "interest_id"}
)
}
)
```
- 요청된 사용자 찾을 수 없음 -> UserNotFoundException
- 요청된 관심사 찾을 수 없음 -> InterestNotFoundException
- 관심사 4개 이상 요청됨 -> UserInterestUpdateRequestSizeExceededException
- 중복된 관심사 …
> [IDLE-195] feat: 사용자 관심사 등록 기능 개발

- frontend/lib/data/datasource/profile/follow_datasource.dart
- frontend/lib/data/datasource/profile/interests_datasource.dart
- frontend/lib/data/datasource/profile/profile_datasource.dart
- frontend/lib/data/datasource/search/search_datasource.dart
- frontend/lib/data/model/profile/follower_response.dart
- frontend/lib/data/model/profile/following_response.dart
- frontend/lib/data/model/profile/profile_common_response.dart
- frontend/lib/data/network/api.dart
- frontend/lib/data/repository/follow_repository.dart
- frontend/lib/res/constants/enum.dart
- frontend/lib/res/constants/style.dart
- frontend/lib/ui/profile/components/profile_header.dart
- frontend/lib/ui/profile/follow/components/follow_layout.dart
- frontend/lib/ui/profile/follow/components/follow_user_info.dart
- frontend/lib/ui/profile/follow/follower_screen.dart
- frontend/lib/ui/profile/my_interests/components/interest_category.dart
- frontend/lib/ui/profile/my_interests/my_interests_screen.dart
- frontend/lib/ui/profile/profile_screen.dart
- frontend/lib/utils/dios/auth_dio.dart
- frontend/lib/utils/dios/dio_service.dart
<div>
</div>
<br>
팔로우(팔로워/팔로잉) 페이지
- 프로필 페이지 UI에 팔로우 api 연동 후 팔로워/팔로잉 숫자 표시
- 팔로워/팔로잉 상단 탭바 구현 및 중첩 스크롤 뷰 구현
- 팔로워 조회 및 삭제 버튼 구현
- 팔로잉 조회 및 팔로잉(언팔로우) 버튼 구현 + 목록 유지 및 팔로우 버튼 구현
<br>
<div>
</div>
<br>
- 가능한 시나리오 테스트를 진행하였습니다.
- 실 기기 테스트 진행 예정입니다.
<br><br>
<br><br>
<br><br>
- 테스트 계정(테스트1~30)으로 진행했고, 임의로 생성한 리스트가 아닙니다..!! (모두 서버의 기본 이미지로 되어있어서 착각할수도,,)
- 최대한 리팩터링을 적용하려고 노력 중이여서, 팔로워/팔로잉 페이지가 아닌 페이지에도 일부 코드 수정이 존재합니다 😅
- UI를 구성하면서 피그마 화면에서 조금 더 개선하는 부분이 있어, 기존 피그마 화면과는 일부 다른 점 양해 부탁드립니다!
- 팔로워, 팔로잉이 현재는 리스트에 추가되는 순서로 들어오는 점이 있는데 정렬 부분에 대해 논의하면 좋을 것 같습니다!
- 다음 이슈도 빠르게 진행해보겠습니다..!
<br>
> [IDLE-177] feat: 팔로우/팔로잉 UI 구현 및 user API 연동

- backend/user-service/.gitignore
- backend/user-service/build.gradle
- backend/user-service/http/User.http
- backend/user-service/src/main/java/kr/mybrary/userservice/UserServiceApplication.java
- backend/user-service/src/main/java/kr/mybrary/userservice/global/config/QueryDslConfig.java
- backend/user-service/src/main/java/kr/mybrary/userservice/user/domain/UserService.java
- backend/user-service/src/main/java/kr/mybrary/userservice/user/domain/UserServiceImpl.java
- backend/user-service/src/main/java/kr/mybrary/userservice/user/domain/dto/request/UserInfoServiceRequest.java
- backend/user-service/src/main/java/kr/mybrary/userservice/user/domain/dto/response/UserInfoServiceResponse.java
- backend/user-service/src/main/java/kr/mybrary/userservice/user/persistence/User.java
- backend/user-service/src/main/java/kr/mybrary/userservice/user/persistence/model/UserInfoModel.java
- backend/user-service/src/main/java/kr/mybrary/userservice/user/persistence/repository/UserRepository.java
- backend/user-service/src/main/java/kr/mybrary/userservice/user/persistence/repository/UserRepositoryCustom.java
- backend/user-service/src/main/java/kr/mybrary/userservice/user/persistence/repository/UserRepositoryCustomImpl.java
- backend/user-service/src/main/java/kr/mybrary/userservice/user/presentation/UserController.java
- backend/user-service/src/main/java/kr/mybrary/userservice/user/presentation/dto/request/UserInfoRequest.java
- backend/user-service/src/main/resources/application-test.yml
- backend/user-service/src/test/java/kr/mybrary/userservice/PersistenceTest.java
- backend/user-service/src/test/java/kr/mybrary/userservice/TestConfig.java
- backend/user-service/src/test/java/kr/mybrary/userservice/global/jwt/service/JwtServiceTest.java
- backend/user-service/src/test/java/kr/mybrary/userservice/interest/persistence/repository/InterestCategoryRepositoryTest.java
- backend/user-service/src/test/java/kr/mybrary/userservice/interest/persistence/repository/InterestRepositoryTest.java
- backend/user-service/src/test/java/kr/mybrary/userservice/interest/persistence/repository/UserInterestRepositoryTest.java
- backend/user-service/src/test/java/kr/mybrary/userservice/user/domain/UserServiceImplTest.java
- backend/user-service/src/test/java/kr/mybrary/userservice/user/persistence/repository/UserRepositoryTest.java
- backend/user-service/src/test/java/kr/mybrary/userservice/user/presentation/UserControllerTest.java
- 요청
- DELETE api/v1/users/account
- header: USER-ID
- 응답
```
{
"status": "200 OK",
"message": "회원 탈퇴에 성공했습니다.",
"data": null
}
```
- 현재 회원 탈퇴 시 단순히 사용자 정보를 soft-delete 처리하고 있습니다. 추후 사용자 탈퇴 시 해당 사용자의 마이북, 마이북리뷰, 획득 뱃지 등을 삭제 처리하기 위한 이벤트 발행을 추가하겠습니다.
- 요청
- GET api/v1/users/info
- request body
```
{
"userIds": [
"loginId1",
"loginId2",
"loginId3"
]
}
```
- 응답
```
{
"status": "200 OK",
"message": "사용자 정보를 모두 조회했습니다.",
"data": {
"userInfoElements": [
{
"userId": "loginId1",
"nickname": "nickname1",
"profileImageUrl": "https://mybrary-user-service.s3.ap-northeast-2.amazonaws.com/profile/profileImage/default.jpg"
},
{
"userId": "loginId2",
"nickname": "nickname2",
"profileImageUrl": "https://mybrary-user-service.s3.ap-northeast-2.amazonaws.com/profile/profileImage/default.jpg"
},
{
"userId": …
```
> [IDLE-173] feat: 회원 탈퇴 기능 개발 (+사용자 정보 조회 기능 개발)

- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/domain/MyBookService.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/persistence/repository/MyBookRepositoryCustom.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/persistence/repository/MyBookRepositoryCustomImpl.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/presentation/MyBookController.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/presentation/dto/response/MyBookRegistrationCountResponse.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/booksearch/domain/AladinBookSearchApiServiceTest.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/mybook/MybookDtoTestData.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/mybook/domain/MyBookReadServiceTest.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/mybook/persistence/MyBookRepositoryTest.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/mybook/presentation/MyBookControllerTest.java
- GET "/api/v1/mybooks/today-registration-count"
- 응답값
```
{
"status": "200 OK",
"message": "서재의 도서 목록입니다.",
"data": {
"count" : 10
}
}
```
<br><br>
<br><br>
🏃‍♂️ 보통 : 최대한 빠르게 리뷰 부탁드립니다.
<br><br>
> [IDLE-200] 오늘 등록한 마이북 갯수 조회 API 개발

- frontend/ios/Runner/Info.plist
- frontend/lib/res/constants/style.dart
- frontend/lib/ui/mybook/components/mybook_header.dart
- frontend/lib/ui/mybook/mybook_detail/components/mybook_detail_record.dart
- frontend/lib/ui/mybook/mybook_detail/components/mybook_edit_review.dart
- frontend/lib/ui/mybook/mybook_detail/mybook_detail_screen.dart
- frontend/lib/ui/mybook/mybook_screen.dart
<div>
</div>
<br>
- 완독 설정 후 데이터 패칭 해결
- 서재 사진 겹치는 순서 해결
- 저장되지 않은 리뷰 팝업창 해결
<br><br>
<br><br>
🏃‍♂️ 보통 : 최대한 빠르게 리뷰 부탁드립니다.
<br><br>
- 마이북 테스트 중 발생한 버그에 대해서 해결하였습니다.
- 기록한 내용이 있을 때, 뒤로가기를 막고 팝업을 띄우는 기능을 추가하였습니다.
<br>
> [IDLE-223] fix: 마이북 테스트 중 버그 해결

- backend/book-service/src/main/java/kr/mybrary/bookservice/client/user/api/UserServiceClient.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/client/user/dto/request/UserInfoRequest.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/client/user/dto/response/UserInfoServiceResponse.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/review/domain/MyReviewReadService.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/review/persistence/repository/MyReviewRepositoryCustomImpl.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/review/MyReviewDtoTestData.java
- backend/user-service/src/main/java/kr/mybrary/userservice/user/presentation/UserController.java
- backend/user-service/src/test/java/kr/mybrary/userservice/user/presentation/UserControllerTest.java
- 기존에 GET을 사용했으나, RequestBody가 있는 경우 GET을 사용하지 못한다. 따라서 GET 대신 POST로 수정
- 실제 user-service에서 응답하는 객체에 맞게 book-service에서도 응답 객체를 준비해야한다.
- user-service에서 유저의 닉네임과 프로필 URL만 반환하지 않고, status, message, body를 반환하기 때문에 아래와 같이 응답 객체 정의
```
@Builder
@Getter
@AllArgsConstructor
@NoArgsConstructor
public class UserInfoServiceResponse {
private String status;
private String message;
private UserInfoList data;
@Builder
@Getter
@AllArgsConstructor
@NoArgsConstructor
public static class UserInfoList {
List<UserInfo> userInfoElements;
}
@Builder
@Getter
@AllArgsConstructor
@NoArgsConstructor
public static class UserInfo {
private String userId;
private String nickname;
private String profileImageUrl;
}
}
```
- 도서에 대한 리뷰 조회 QueryDsl에 where절이 빠져있어, 추가.
- 탈퇴한 회원에 있어서 응답 값 생성시, NPE가 발생하여, filter를 통해 예외처리 …
> [IDLE-224] FeignClient 이슈 해결

- frontend/lib/data/datasource/home/home_datasource.dart
- frontend/lib/data/model/home/book_list_by_category_response.dart
- frontend/lib/data/model/home/home_common_response.dart
- frontend/lib/data/model/home/today_registered_book_count_response.dart
- frontend/lib/data/network/api.dart
- frontend/lib/data/repository/home_repository.dart
- frontend/lib/res/constants/color.dart
- frontend/lib/res/constants/config.dart
- frontend/lib/res/constants/style.dart
- frontend/lib/ui/home/components/home_barcode_button.dart
- frontend/lib/ui/home/components/home_best_seller.dart
- frontend/lib/ui/home/components/home_book_count.dart
- frontend/lib/ui/home/components/home_intro.dart
- frontend/lib/ui/home/components/home_recommend_books.dart
- frontend/lib/ui/home/home_screen.dart
- frontend/lib/ui/mybook/mybook_screen.dart
- frontend/lib/utils/logics/common_utils.dart
<div>
</div>
<br>
홈 메인 페이지
- 오늘 마이브러리에 등록된 책 수 표시 UI 구현 및 api 연동
- 이번 주 베스트 셀러 UI 구현 및 api 연동
- 마이북 등록 후 뒤로가기 시 등록된 책 수 재 카운팅
- 카테고리 별 추천 도서 UI 구현 및 api 임시 연동
- 카테고리 도서 목록 스크롤 후 다른 카테고리 선택 시 스크롤 초기화 (UX)
<br><br>
<br><br>
🏃‍♂️ 보통 : 최대한 빠르게 리뷰 부탁드립니다.
<br><br>
- 피그마와 조금 다르게 오늘 등록된 책의 자릿수를 6자리로 설정하였습니다.
- 카테고리 (관심사) 별 추천 도서 UI 구현 및 조회가 잘 되는지 여부를 확인하기 위해 3개의 임시 카테고리로 조회합니다.
- 추후 api 개발되면 수정하도록 하겠습니다!
<br>
> [IDLE-178] feat: 메인 화면(홈) UI 구현 및 user&book API 연동

- frontend/lib/data/datasource/search/search_datasource.dart
- frontend/lib/data/model/search/search_common_data.dart
- frontend/lib/data/model/search/user_search_response.dart
- frontend/lib/data/network/api.dart
- frontend/lib/data/repository/search_repository.dart
- frontend/lib/res/constants/style.dart
- frontend/lib/ui/search/components/search_popular_keyword.dart
- frontend/lib/ui/search/search_book_list/components/search_book_list_info.dart
- frontend/lib/ui/search/search_book_list/components/search_user_info.dart
- frontend/lib/ui/search/search_book_list/components/search_user_layout.dart
- frontend/lib/ui/search/search_book_list/search_book_list.dart
- frontend/lib/ui/search/search_detail/components/book_detail_header.dart
- frontend/lib/ui/search/search_detail/components/book_detail_info.dart
- frontend/lib/ui/search/search_detail/search_detail_screen.dart
- frontend/lib/ui/search/search_screen.dart
- frontend/lib/utils/dios/auth_dio.dart
- frontend/pubspec.lock
<div>
</div>
<br>
검색 페이지
- 기존 단일 도서 검색 목록 화면에서 좌우 스와이프 스크롤 형태로 변경
- 사용자 검색 UI 구현 및 api 연동
- 사용자 검색 스크롤에 bounce 애니메이션 적용
- 추후 확장성을 고려하여 futureBuilder를 도서 검색과 사용자 검색 각각 분리
<br>
이슈 해결 사항
- 기존 로직은 도서 검색에서 scroll notification 으로 스크롤이 모바일 하단에 닿을 시 nextRequestUrl 요청
- 검색 페이지 변경에 따라 사용자 검색에서도 스크롤이 모바일 하단에 닿으면 도서 무한 스크롤이 요청되는 이슈 발생
- scroll 컨트롤러를 도서 검색 목록에만 할당하고, notification 위젯은 삭제
- 이후, 도서 검색 무한 스크롤도 잘 되면서 사용자 검색에서는 더 이상 도서 관련 요청을 보내지 않도록 해결
<br><br>
<div>
</div>
<br>
- 검색 메인 화면과 동일한 헤더 컴포넌트로 수정하였습니다.
- 도서 전체 및 사용자 결과와 동시에 검색이 가능합니다.
<br><br>
<br><br>
🐢 천천히 : 급하지 않습니다. 
<br><br>
- 다음 진행할 [IDLE-210] 에서 타 사용자 프로필 컴포넌트가 구현되면, 사용자 검색에서도 클릭시 해당 유저의 프로필로 연동할 예정입니다.
- 사용자 검색 결과가 없을 때, 빈 리스트로 받게 되면(현재는 에러코드) gif처럼 결과가 없습니다로 나올 예정입니다.
- 도서 검색 결과가 없을 때도 빈 리스트로 받게 되면 검색된 책이 없습니다로 나올 예정입니다.
<br>
[IDLE-210]: …
> [IDLE-209] feat: 사용자 검색 UI 구현 및 API 연동

- backend/book-service/src/main/java/kr/mybrary/bookservice/book/domain/dto/BookDtoMapper.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/book/persistence/Book.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/booksearch/domain/AladinBookSearchApiService.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/booksearch/domain/KakaoBookSearchApiService.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/domain/MyBookService.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/persistence/MyBook.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/persistence/repository/MyBookRepository.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/review/domain/MyReviewWriteService.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/book/BookFixture.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/book/domain/dto/BookDtoMapperTest.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/booksearch/domain/AladinBookSearchApiServiceTest.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/booksearch/domain/KakaoBookSearchApiServiceTest.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/mybook/MybookDtoTestData.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/mybook/domain/MyBookReadServiceTest.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/mybook/persistence/MyBookRepositoryTest.java
- backend/book-service/src/test/java/kr/mybrary/bookservice/review/domain/MyReviewWriteServiceTest.java
요구 사항을 제대로 반영하지 못해서 죄송합니다ㅠ 앞으로 기능 개발시, 요구 사항을 명확하게 정리해서 개발해보도록 하겠습니다!
- 도서 상세 조회시, 사용자가 해당 도서를 완독하였다면, true를 반환하도록 로직 수정
- 읽기전/읽는중 -> 완독 : 도서 엔티티의 완독수 + 1
- 완독 -> 읽기전.읽는중 : 도서 엔티티의 완독수 - 1
- 리뷰 작성 : 도서 엔티티의 리뷰 갯수 + 1 and 리뷰 별점 + 사용자가 입력한 리뷰 별점
- 리뷰 수정 : 도서 엔티티의 리뷰 별점 = 도서 엔티티의 리뷰 별점 - 기존 사용자의 리뷰 별점 + 변경한 사용자의 리뷰 별점
- 리뷰 삭제 : 도서 엔티티의 리뷰 갯수 - 1 and 리뷰 별점 - 기존 사용자의 리뷰 별점
- 도서 엔티티의 리뷰 별점은 총 사용자의 별점의 합으로 저장
- 따라서 도서 상세 보기 조회시, starRating을 별점 총합 / 리뷰 갯수로 별점의 평균을 반환한다. (소수점 첫째자리까지)
- 기존에는 키워드로 도서 검색시, 도서 결과가 없으면 예외를 던졌지만,
- 결과가 없을 시, 빈 리스트를 반환하도록 수정
- isbn13으로 도서 상세 조회시 결과가 없는 경우는 그전과 동일하게 예외를 던진다.
<br><br>
<br><br>
🚨 긴급 : 선 어프루브 후 리뷰를 부탁드립니다. (리뷰는 추후 반영) 
<br><br>
> [IDLE-227] 도서 관련 버그 수정

- backend/user-service/build.gradle
- backend/user-service/src/main/java/kr/mybrary/userservice/authentication/domain/oauth2/service/CustomOAuth2UserService.java
- backend/user-service/src/main/java/kr/mybrary/userservice/global/constant/ImageConstant.java
- backend/user-service/src/main/java/kr/mybrary/userservice/global/util/MultipartFileUtil.java
- backend/user-service/src/main/java/kr/mybrary/userservice/user/domain/UserService.java
- backend/user-service/src/main/java/kr/mybrary/userservice/user/domain/UserServiceImpl.java
- backend/user-service/src/main/java/kr/mybrary/userservice/user/domain/dto/UserMapper.java
- backend/user-service/src/main/java/kr/mybrary/userservice/user/domain/dto/request/ProfileImageUpdateServiceRequest.java
- backend/user-service/src/main/java/kr/mybrary/userservice/user/domain/dto/request/ProfileImageUrlServiceRequest.java
- backend/user-service/src/main/java/kr/mybrary/userservice/user/domain/dto/response/UserInfoServiceResponse.java
- backend/user-service/src/main/java/kr/mybrary/userservice/user/domain/exception/profile/ProfileImageSizeOptionNotSupportedException.java
- backend/user-service/src/main/java/kr/mybrary/userservice/user/domain/storage/AmazonS3Service.java
- backend/user-service/src/main/java/kr/mybrary/userservice/user/domain/storage/StorageService.java
- backend/user-service/src/main/java/kr/mybrary/userservice/user/persistence/User.java
- backend/user-service/src/main/java/kr/mybrary/userservice/user/presentation/UserController.java
- backend/user-service/src/test/java/kr/mybrary/userservice/user/UserFixture.java
- backend/user-service/src/test/java/kr/mybrary/userservice/user/UserTestData.java
- backend/user-service/src/test/java/kr/mybrary/userservice/user/domain/UserServiceImplTest.java
- backend/user-service/src/test/java/kr/mybrary/userservice/user/domain/dto/UserMapperTest.java
- backend/user-service/src/test/java/kr/mybrary/userservice/user/presentation/UserControllerTest.java
- 기존: profile/profileImage/userId.jpg
- 변경: profile/profileImage/userId/2023-08-21_16-21-34-146.jpg
- 기존 이미지에 덮어씌우지 않고 수정 일시의 타임스탬프 파일명으로 새로운 파일을 업로드합니다.
- 저장된 파일이 너무 많다 싶으면 한 달 간격으로 예전 파일을 삭제하는 것도 고려해보겠습니다.
- profile/profileImage/ 에 새로운 파일이 올라오면 해당 파일을 리사이징 하여 resized 버킷에 저장하는 lambda 함수를 추가했습니다.
- 현재 리사이징은 1/20 로 축소하는 tiny와 1/10 로 축소하는 small이 있습니다.
- 리사이징 함수는 다음과 같습니다.
```
def resize_image_tiny(image_path, resized_path):
with Image.open(image_path) as image:
image.thumbnail(tuple(x / 20 for x in image.size))
image.save(resized_path)
def resize_image_small(image_path, resized_path):
with Image.open(image_path) as image:
image.thumbnail(tuple(x / 10 for x in image.size))
image.save(resized_path)
def lambda_handler(event, context):
for record in event['Records']:
bucket = …
```
> [IDLE-230] 프로필 이미지 저장/조회 로직 수정

- backend/book-service/src/main/java/kr/mybrary/bookservice/mybook/presentation/MyBookController.java
- 앱 테스트 중, 다른 사용자의 프로필에서 마이북을 조회했을 때
- 방문한 사용자의 마이북 목록이 아니라
- 로그인한 사용자의 마이북 목록이 보여졌습니다.
- 마이북 목록 조회 Controller에서 서비스 요청 DTO를 생성할 때
- 생성자의 매개변수 순서가 바뀌었기 때문입니다.
- userId 와 loginId의 순서를 바꾸어줬습니다.
<br><br>
<br><br>
🚨 긴급 : 선 어프루브 후 리뷰를 부탁드립니다. (리뷰는 추후 반영)
<br><br>
- 테스트 코드는 요청 DTO가 any()로 모킹 되어 있었기에 수정 작업이 없습니다.
> [IDLE-231] fix: 마이북 목록 조회 API 수정

- backend/book-service/build.gradle
- backend/book-service/src/main/java/kr/mybrary/bookservice/booksearch/domain/AladinBookSearchApiService.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/booksearch/domain/exception/AladinApiUnavailableException.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/client/user/api/UserServiceClient.java
- backend/book-service/src/main/java/kr/mybrary/bookservice/global/config/Resilience4jConfig.java
- backend/book-service/src/main/resources/application-dev.yml
- backend/book-service/src/main/resources/application-local.yml
- backend/book-service/src/main/resources/application-resilience4j.yml
- backend/book-service/src/test/java/kr/mybrary/bookservice/booksearch/domain/AladinBookSearchApiServiceTest.java
- `Resilience4j` 사용하였습니다. 아래는 한글로 번역된 문서와 공식문서입니다.
- https://godekdls.github.io/Spring%20Cloud%20Circuit%20Breaker/contents/
- https://resilience4j.readme.io/docs
```
userServiceFeignClientRetryConfig:
maxAttempts: 3
waitDuration: 1000
retryExceptions:
- java.net.UnknownHostException
- java.net.SocketTimeoutException
- java.net.ConnectException
- feign.RetryableException
- feign.FeignException.InternalServerError
- feign.FeignException.BadGateway
- feign.FeignException.GatewayTimeout
- feign.FeignException.TooManyRequests
```
```
2023-08-29T05:27:57.455+09:00  WARN 61321 --- [nio-8080-exec-1] o.s.c.l.core.RoundRobinLoadBalancer      : No servers available for service: user-service
2023-08-29T05:27:57.457+09:00  WARN 61321 --- [nio-8080-exec-1] RetryableFeignBlockingLoadBalancerClient : …
```
> [IDLE-228] Resilience4j Retry, CircuitBreaker 적용
